# Generated by Django 3.1.6 on 2021-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='hands',
            field=models.CharField(max_length=255),
        ),
    ]
