# Generated by Django 3.1.6 on 2021-02-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210222_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
        migrations.AddField(
            model_name='deal',
            name='username',
            field=models.CharField(default='testuser', max_length=32),
            preserve_default=False,
        ),
    ]
