# Generated by Django 3.1.6 on 2021-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210224_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ai_bid',
            field=models.CharField(default='DFLT', max_length=10),
            preserve_default=False,
        ),
    ]
