# Generated by Django 3.1.7 on 2021-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_deal_ai_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='ai_bid',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='bid',
        ),
        migrations.AddField(
            model_name='deal',
            name='auction',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
