# Generated by Django 3.1.7 on 2021-03-29 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210329_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
